CREATE TYPE "channelType" AS ENUM (
  'messenger',
  'whatsapp',
  'telegram',
  'sms'
);

CREATE TYPE "conversationStatus" AS ENUM (
  'started',
  'assigned',
  'closed'
);

CREATE TYPE "agentStatus" AS ENUM (
  'online',
  'offline'
);

CREATE TABLE "conversation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_phone_number" int NOT NULL,
  "agent_id" int NOT NULL,
  "channel_type" channelType NOT NULL,
  "reason" varchar NOT NULL,
  "waiting_time" varchar,
  "processing_time" varchar,
  "total_time" varchar,
  "status" conversationStatus DEFAULT 'started',
  "is_deleted" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "conversation_detail" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" int,
  "content" varchar
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" varchar,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "picture" varchar,
  "role" int DEFAULT 3,
  "status" agentStatus DEFAULT 'offline',
  "is_deleted" varchar DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "permission" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int,
  "module_id" int,
  "all" int DEFAULT 0,
  "list" int DEFAULT 1,
  "override" int DEFAULT 1,
  "remove" int DEFAULT 0,
  "is_deleted" varchar DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" int NOT NULL,
  "name" varchar NOT NULL,
  "is_deleted" varchar DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "module" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" int NOT NULL,
  "name" varchar NOT NULL,
  "is_deleted" varchar DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

ALTER TABLE "conversation_detail" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversation" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("role") REFERENCES "role" ("id");

ALTER TABLE "permission" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "permission" ADD FOREIGN KEY ("module_id") REFERENCES "module" ("id");

ALTER TABLE "conversation" ADD FOREIGN KEY ("agent_id") REFERENCES "user" ("id");
